<?php

namespace Database\Seeders;

use App\Models\Tenant\TenantSetting;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountTreesSeeder extends Seeder
{
    public function run(): void
    {
        $connection = DB::connection('tenant');

        $existingAccountsCount = $connection
            ->table('account_trees')
            ->whereNull('deleted_at')
            ->count();

        if ($existingAccountsCount > 0) {
            return;
        }

        $now = Carbon::now();
        $accountIdsByCode = [];

        $accounts = [
            [
                'parent_code' => null,
                'account_name' => 'الأصول',
                'account_code' => '1',
                'account_type' => 'debit',
                'level' => 1,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => null,
                'account_name' => 'الخصوم',
                'account_code' => '2',
                'account_type' => 'credit',
                'level' => 1,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => null,
                'account_name' => 'حقوق الملكية',
                'account_code' => '3',
                'account_type' => 'credit',
                'level' => 1,
                'income_general_statement' => 'general',
                'order' => 3,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => null,
                'account_name' => 'الإيرادات',
                'account_code' => '4',
                'account_type' => 'credit',
                'level' => 1,
                'income_general_statement' => 'income',
                'order' => 4,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => null,
                'account_name' => 'المصروفات',
                'account_code' => '5',
                'account_type' => 'debit',
                'level' => 1,
                'income_general_statement' => 'income',
                'order' => 5,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '1',
                'account_name' => 'الأصول المتداولة',
                'account_code' => '11',
                'account_type' => 'debit',
                'level' => 2,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '1',
                'account_name' => 'الأصول غير المتداولة',
                'account_code' => '12',
                'account_type' => 'debit',
                'level' => 2,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '11',
                'account_name' => 'النقدية وما في حكمها',
                'account_code' => '110',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '11',
                'account_name' => 'الذمم المدينة',
                'account_code' => '120',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '11',
                'account_name' => 'ضريبة قيمة مضافة مدينة',
                'account_code' => '130',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 3,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '11',
                'account_name' => 'مصروفات مدفوعة مقدماً وأخرى',
                'account_code' => '140',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 4,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '11',
                'account_name' => 'المخزون',
                'account_code' => '150',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 5,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '110',
                'account_name' => 'نقدية بالصندوق',
                'account_code' => '1101',
                'account_type' => 'debit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '110',
                'account_name' => 'النقدية لدى البنوك',
                'account_code' => '1102',
                'account_type' => 'debit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '110',
                'account_name' => 'المحافظ الإلكترونية',
                'account_code' => '1103',
                'account_type' => 'debit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 3,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '120',
                'account_name' => 'العملاء',
                'account_code' => '1201',
                'account_type' => 'debit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '120',
                'account_name' => 'ذمم مدينة أخرى',
                'account_code' => '1202',
                'account_type' => 'debit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '12',
                'account_name' => 'الأصول الثابتة',
                'account_code' => '1210',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '12',
                'account_name' => 'مجمع الإهلاك',
                'account_code' => '1290',
                'account_type' => 'credit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '1210',
                'account_name' => 'أثاث وتجهيزات',
                'account_code' => '12101',
                'account_type' => 'debit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '1210',
                'account_name' => 'أجهزة ومعدات',
                'account_code' => '12102',
                'account_type' => 'debit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '1210',
                'account_name' => 'وسائل نقل',
                'account_code' => '12103',
                'account_type' => 'debit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 3,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '1290',
                'account_name' => 'مجمع إهلاك أثاث وتجهيزات',
                'account_code' => '12901',
                'account_type' => 'credit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '1290',
                'account_name' => 'مجمع إهلاك أجهزة ومعدات',
                'account_code' => '12902',
                'account_type' => 'credit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '1290',
                'account_name' => 'مجمع إهلاك وسائل نقل',
                'account_code' => '12903',
                'account_type' => 'credit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 3,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '2',
                'account_name' => 'الخصوم المتداولة',
                'account_code' => '21',
                'account_type' => 'credit',
                'level' => 2,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '2',
                'account_name' => 'الخصوم غير المتداولة',
                'account_code' => '22',
                'account_type' => 'credit',
                'level' => 2,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '21',
                'account_name' => 'ذمم دائنة / موردون',
                'account_code' => '2101',
                'account_type' => 'credit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '21',
                'account_name' => 'ضريبة قيمة مضافة للمبيعات',
                'account_code' => '2103',
                'account_type' => 'credit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '21',
                'account_name' => 'مصاريف مستحقة الدفع',
                'account_code' => '2104',
                'account_type' => 'credit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 3,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '21',
                'account_name' => 'حساب تسوية ضريبة القيمة المضافة',
                'account_code' => '2105',
                'account_type' => 'credit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 4,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '2101',
                'account_name' => 'الموردون - عام',
                'account_code' => '210101',
                'account_type' => 'credit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '22',
                'account_name' => 'قروض طويلة الأجل',
                'account_code' => '2201',
                'account_type' => 'credit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '22',
                'account_name' => 'أطراف ذات علاقة - دائن',
                'account_code' => '2202',
                'account_type' => 'credit',
                'level' => 3,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '3',
                'account_name' => 'رأس المال',
                'account_code' => '3101',
                'account_type' => 'credit',
                'level' => 2,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '3',
                'account_name' => 'جاري الشركاء',
                'account_code' => '3102',
                'account_type' => 'credit',
                'level' => 2,
                'income_general_statement' => 'general',
                'order' => 2,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '3',
                'account_name' => 'أرباح مرحلة',
                'account_code' => '3103',
                'account_type' => 'credit',
                'level' => 2,
                'income_general_statement' => 'general',
                'order' => 3,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '3',
                'account_name' => 'ملخص الدخل',
                'account_code' => '3901',
                'account_type' => 'credit',
                'level' => 2,
                'income_general_statement' => 'general',
                'order' => 4,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '4',
                'account_name' => 'إيرادات المبيعات',
                'account_code' => '4101',
                'account_type' => 'credit',
                'level' => 2,
                'income_general_statement' => 'income',
                'order' => 1,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '4',
                'account_name' => 'إيرادات خدمات',
                'account_code' => '4102',
                'account_type' => 'credit',
                'level' => 2,
                'income_general_statement' => 'income',
                'order' => 2,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '4',
                'account_name' => 'إيرادات عمولات',
                'account_code' => '4103',
                'account_type' => 'credit',
                'level' => 2,
                'income_general_statement' => 'income',
                'order' => 3,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '4',
                'account_name' => 'مردودات / استرجاعات',
                'account_code' => '4191',
                'account_type' => 'debit',
                'level' => 2,
                'income_general_statement' => 'income',
                'order' => 4,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '5',
                'account_name' => 'مصروفات تشغيل',
                'account_code' => '5100',
                'account_type' => 'debit',
                'level' => 2,
                'income_general_statement' => 'income',
                'order' => 1,
                'main_acc_status' => 'main',
            ],
            [
                'parent_code' => '5100',
                'account_name' => 'رواتب وأجور',
                'account_code' => '5101',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'income',
                'order' => 1,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '5100',
                'account_name' => 'إيجارات',
                'account_code' => '5102',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'income',
                'order' => 2,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '5100',
                'account_name' => 'مرافق وخدمات',
                'account_code' => '5103',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'income',
                'order' => 3,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '5100',
                'account_name' => 'تسويق ومبيعات',
                'account_code' => '5104',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'income',
                'order' => 4,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '5100',
                'account_name' => 'عمولات بنكية / بوابات دفع',
                'account_code' => '5105',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'income',
                'order' => 5,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '5100',
                'account_name' => 'إهلاك',
                'account_code' => '5106',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'income',
                'order' => 6,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '5100',
                'account_name' => 'ديون معدومة / مشكوك فيها',
                'account_code' => '5107',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'income',
                'order' => 7,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '5100',
                'account_name' => 'رسوم حكومية / ضرائب',
                'account_code' => '5108',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'income',
                'order' => 8,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '150',
                'account_name' => 'مخزون بضائع',
                'account_code' => '1501',
                'account_type' => 'debit',
                'level' => 4,
                'income_general_statement' => 'general',
                'order' => 1,
                'main_acc_status' => 'sub',
            ],
            [
                'parent_code' => '5100',
                'account_name' => 'تكلفة المبيعات',
                'account_code' => '5110',
                'account_type' => 'debit',
                'level' => 3,
                'income_general_statement' => 'income',
                'order' => 9,
                'main_acc_status' => 'sub',
            ],
        ];

        foreach ($accounts as $account) {
            $parentCode = $account['parent_code'];

            $id = $connection->table('account_trees')->insertGetId([
                'parent_id' => $parentCode ? ($accountIdsByCode[$parentCode] ?? null) : null,
                'account_name' => $account['account_name'],
                'account_code' => $account['account_code'],
                'account_type' => $account['account_type'],
                'level' => $account['level'],
                'branch_id' => null,
                'income_general_statement' => $account['income_general_statement'],
                'balance_side' => null,
                'is_disabled' => false,
                'order' => $account['order'],
                'main_acc_status' => $account['main_acc_status'],
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            $accountIdsByCode[$account['account_code']] = $id;
        }

        $defaultSettings = [
            'clients_account_tree_id' => '1201',
            'suppliers_account_tree_id' => '210101',
            'accounts_center_account_tree_id' => '5100',
            'income_summary_account_tree_id' => '3901',
            'retained_earnings_account_tree_id' => '3103',
            'sales_revenue_account_tree_id' => '4101',
            'sales_returns_account_tree_id' => '4191',
            'inventory_account_tree_id' => '1501',
            'cogs_account_tree_id' => '5110',
            'sales_tax_payable_account_tree_id' => '2103',
            'purchase_tax_receivable_account_tree_id' => '130',
            'default_cash_account_tree_id' => '1101',
            'default_bank_account_tree_id' => '1102',
            'default_wallet_account_tree_id' => '1103',
            'walk_in_ar_account_tree_id' => '1202',
        ];

        foreach ($defaultSettings as $key => $accountCode) {
            if (isset($accountIdsByCode[$accountCode])) {
                TenantSetting::setValue($key, $accountIdsByCode[$accountCode]);
            }
        }
    }
}
